// AUTOGENERATED FILE. DO NOT MODIFY.
// Generated via `npm run gen-shmem`

// Instance: ef6786ec-24fd-4a0f-9ecd-d8c650a5617e

#pragma once
#include <stdint.h>

#define FIRMWARE_IDENT 21

struct Data {
  // uint8_t firmwareIdent;
  // uint8_t status;
  // bool heartbeat;
  // uint16_t batteryMillivolts;
  int16_t Motor1;
  int16_t Motor2;
  int16_t Motor3;
  int16_t Motor4;
  int16_t Motor5;
  int16_t Motor6;
  bool resetEncoder1;
  bool resetEncoder2;
  bool resetEncoder3;
  bool resetEncoder4;
  bool resetEncoder5;
  bool resetEncoder6;
  int16_t Encoder1;
  int16_t Encoder2;
  int16_t Encoder3;
  int16_t Encoder4;
  int16_t Encoder5;
  int16_t Encoder6;
};
